# Generated by Django 4.0.1 on 2022-04-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivemodel',
            options={'verbose_name': '压缩包', 'verbose_name_plural': '[01].压缩包'},
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000, verbose_name='文件名')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.archivemodel', verbose_name='压缩包')),
            ],
        ),
    ]
